### ISSUE TITLE
1.15.2 server forge 21.2.0 crash

### ISSUE THREAD

**Issue by KuroNoSeiHai** [ProjectEssentials/ProjectEssentials-Core#9]
Hi, I use Project.Essentials.Core-MOD-2.0.1+MC-1.15.2 and Project.Essentials.Permissions-2.0.0-RC.1+MC-1.15.2.
When I start the server it crashed.Below is crash report.\
---- Minecraft Crash Report ----
// Why did you do that?

Time: 20-6-6 下午7:37
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: com/mairwunnx/projectessentials/core/api/v1/events/internal/ProcessorEventData
	at com.mairwunnx.projectessentials.permissions.impl.ModuleObject$subscribeEvents$2.invoke(ModuleObject.kt:37) ~[?:2.0.0-RC.1+MC-1.15.2] {re:classloading}
	at com.mairwunnx.projectessentials.core.api.v1.events.ModuleEventAPI.fire(ModuleEventAPI.kt:33) ~[?:2.0.1+MC-1.15.2] {re:classloading}
	at com.mairwunnx.projectessentials.core.api.v1.module.ModuleAPI.initializeOrdered$Project_Essentials_Core(ModuleAPI.kt:73) ~[?:2.0.1+MC-1.15.2] {re:classloading}
	at com.mairwunnx.projectessentials.core.EntryPoint.onServerPreStart(EntryPoint.kt:45) ~[?:2.0.1+MC-1.15.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_3_EntryPoint_onServerPreStart_FMLServerAboutToStartEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:89) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:203) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251] {}
Caused by: java.lang.ClassNotFoundException: com.mairwunnx.projectessentials.core.api.v1.events.internal.ProcessorEventData
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_251] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.1.0.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251] {}
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8066154520 bytes (7692 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 3
	JVM Flags: 10 total; -Xms8g -Xmx8g -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+UseG1GC -XX:SurvivorRatio=6 -XX:G1ReservePercent=15 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=1 -XX:InitiatingHeapOccupancyPercent=40
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.0
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.0-server.jar Minecraft {minecraft@1.15.2 DONE}
		SereneSeasons-1.15.2-3.0.0.68-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.68 DONE}
		openbackup-1.15.1-0.0.0.2.jar OpenBackup {openbackup@1.15.1-0.0.0.2 DONE}
		HardcoreRevival_1.15.2-4.0.0.jar Hardcore Revival {hardcorerevival@4.0.0 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		Bookshelf-1.15.2-5.3.9.jar Bookshelf {bookshelf@5.3.9 DONE}
		RingOfTeleport-1.15.2-1.1.21.jar Ring of Teleport {ring_of_teleport@1.1.21 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		nccreepers_1.15.2-1.1.jar Naturally Charged Creepers {nccreepers@1.1 DONE}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c DONE}
		creeperfix-1.15.2-1.3.jar CreeperFix {creeperfix@1.3 DONE}
		WorldProtector+1.15.2.jar WorldProtector {worldprotector@1.0 DONE}
		BetterBurning-1.15.2-1.3.1.jar BetterBurning {betterburning@1.3.1 DONE}
		strongfarmland-1.15.2-1.0.0.jar Stronger Farmland Mod {strongfarmland@1.15.2-1.0.0 DONE}
		bettertridentreturn-1.15.2-1.0.1.jar Better Trident Return {bettertridentreturn@1.0.1 DONE}
		forge-1.15.2-31.2.0-universal.jar Forge {forge@31.2.0 DONE}
		QuickLeafDecay-MC1.15.2-1.2.5.jar Quick Leaf Decay {quickleafdecay@1.2.5 DONE}
		ffenchants-1.15.2-1.3.1(CN).jar FlashFyre's Enchantments {ffenchants@1.3.1 DONE}
		BowInfinityFix-1.15.2-rv8.jar Bow Infinity Fix {bowinfinityfix@rv8 DONE}
		Project.Essentials.Permissions-2.0.0-RC.1+MC-1.15.2.jar Project Essentials Permissions {project_essentials_permissions@2.0.0-RC.1+MC-1.15.2 DONE}
		gravestone-1.17.3.jar Gravestone Mod {gravestone@1.17.3 DONE}
		Project.Essentials.Core-MOD-2.0.1+MC-1.15.2.jar Project Essentials Core {project_essentials_core@2.0.1+MC-1.15.2 DONE}
		infernalmobs-1.15.1.1(CN).jar Infernal Mobs {infernalmobs@1.15.1.1 DONE}
		corail_recycler-4.0.3-1.15.2(CN).jar Corail Recycler {corail_recycler@4.0.3 DONE}
	Player Count: 0 / 20; []
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by MairwunNx** [comment]
This bug was resolved yesterday, wait for releases (with fixes and others) today. 🎉

**Comment by MairwunNx** [comment]
Changes included in `2.0.2` core and permissions module (`rc.2`). Wait for release for 1 hour.

**Comment by KuroNoSeiHai** [comment]
Thanks!

**Comment by MairwunNx** [comment]
Core `2.0.2` released, with included fix. Wait for Permissions module `rc.2`, it's also no take much time.

Thanks for testing!

**Comment by MairwunNx** [comment]
Permissions module released now, rc.2 including fix for this issue.

Other modules also will released in 30 minutes (but other currently is snapshots and snapshots releases only for 1.14.4). (Except `Basic` module)

**Comment by KuroNoSeiHai** [comment]
Thanks, Servers starts fine now. I testing now, if I find other bugs, I will tell you.
